kafka:
  image: localhost:5000/kafka
  hostname: kafka
  mem_limit: 256000000
  environment:
#    ADVERTISED_HOST : 172.17.8.101 #either 'boot2docker ip' or vagrant address
    ADVERTISED_PORT : 9092
  expose:
    - 2181
    - 9092
  ports:
    - 2181:2181
    - 9092:9092
  volumes:
    - /Working/HadoopHackathon/SparkStreamTradeReactor/Kafka/data:/tmp
    - /Working/HadoopHackathon/SparkStreamTradeReactor/Hadoop/data/datanode1:/shared

tradegen:
  image: localhost:5000/tradegenerator
  hostname: tradegen
  mem_limit: 200000000
  links:
    - kafka
  environment:
    KAFKA: kafka
  command: node TradeGenerator.js

master:
  image: localhost:5000/spark
  mem_limit: 1200000000
  command: /usr/spark/bin/spark-class org.apache.spark.deploy.master.Master -h master
  hostname: master
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
    - 4040
    - 8080
    - 50070
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
    - 50070:50070
  volumes:
    - /Working/HadoopHackathon/SparkStreamTradeReactor/Hadoop/data/namenode:/shared

worker1:
  image: localhost:5000/spark
  mem_limit: 1200000000
  command: /usr/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker1
  environment:
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 1g
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - $HOME/docker_files:/zeppelin/data
    - /Working/HadoopHackathon/SparkStreamTradeReactor/Hadoop/data/datanode2:/shared
