kafka:
  image: localhost:5000/kafka
  hostname: kafka
  mem_limit: 256000000
  command: bash run.sh
  environment:
#    ADVERTISED_HOST : 172.17.8.101 #either 'boot2docker ip' or vagrant address
    ADVERTISED_PORT : 9092
  links:
    - namenode
  expose:
    - 2181
    - 9092
  ports:
    - 2181:2181
    - 9092:9092
  volumes:
    - ~/Working/HadoopHackathon/SparkStreamTradeReactor/Kafka/data:/tmp

tradegen:
  image: localhost:5000/tradegenerator
  hostname: tradegen
  mem_limit: 200000000
  links:
    - kafka
  environment:
    KAFKA: kafka
  command: node TradeGenerator.js
  volumes:
    - ~/Working/HadoopHackathon/SparkStreamTradeReactor/TradeGenerator:/shared

master:
  image: localhost:5000/spark
  mem_limit: 1200000000
  command: /usr/spark/bin/spark-class org.apache.spark.deploy.master.Master -h master
  hostname: master
  links:
    - namenode
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
    - 4040
    - 8080
    - 50070
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
    - 50071:50070

worker1:
  image: localhost:5000/spark
  mem_limit: 1200000000
  command: /usr/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker1
  environment:
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 1g
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - master
    - namenode
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - $HOME/docker_files:/zeppelin/data
    - ~/Working/HadoopHackathon/SparkStreamTradeReactor/Hadoop/data/datanode2:/shared

namenode:
  image: localhost:5000/hadoop
  hostname: namenode
  volumes:
    - ~/Working/HadoopHackathon/SparkStreamTradeReactor/Hadoop/data/namenode:/shared
  ports:
    - "8020:8020"
    - "50070:50070"
  command: hdfs namenode

datanode1:
  image: localhost:5000/hadoop
  hostname: datanode1
  volumes:
      - ~/Working/HadoopHackathon/SparkStreamTradeReactor/Hadoop/data/datanode1:/shared
  links:
      - namenode
  ports:
      - "5001:50075"
  command: hdfs datanode

datanode2:
  image: localhost:5000/hadoop
  hostname: datanode2
  volumes:
      - ~/Working/HadoopHackathon/SparkStreamTradeReactor/Hadoop/data/datanode2:/shared
  links:
      - namenode
  ports:
      - "5002:50075"
  command: hdfs datanode

cadvisor:
  image: google/cadvisor:latest
  hostname: cadvisor
  volumes:
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  ports:
    - 8888:8080

dockerui:
  image: dockerui/dockerui
  hostname: dockerui
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - 9000:9000
